# Import FastAPI framework to build REST APIs
from fastapi import FastAPI

# Import route modules (each module groups related endpoints)
# This keeps the code modular and scalable instead of putting everything in one file
from app.api import routes_embeddings, routes_search, routes_prompts, routes_analysis

# Initialize FastAPI application
# The title appears in the autogenerated Swagger UI (/docs)
app = FastAPI(title="Prompt Similarity Service")

# Register the embeddings routes
# Handles:
# - Generating embeddings for prompts
# - Possibly re-indexing or updating embeddings
# Endpoint prefix: /api/embeddings/*
app.include_router(routes_embeddings.router, prefix="/api/embeddings")

# Register semantic search routes
# Handles:
# - Query-based semantic search over prompts
# Example: "find prompts related to error handling"
# Endpoint prefix: /api/search/*
app.include_router(routes_search.router, prefix="/api/search")

# Register prompt-specific routes
# Handles:
# - Finding similar prompts given a prompt_id
# - Prompt-level operations
# Endpoint prefix: /api/prompts/*
app.include_router(routes_prompts.router, prefix="/api/prompts")

# Register analysis routes
# Handles:
# - Duplicate detection
# - Clustering similar prompts
# - Optimization insights
# Endpoint prefix: /api/analysis/*
app.include_router(routes_analysis.router, prefix="/api/analysis")
